name: research
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - cudatoolkit=10.1
  - cudnn=7.6
  - h5py
  - hdf5
  - alembic
  - altair
  - altair_saver
  - altair_viewer
  - black
  - bokeh
  - boto3
  - catboost
  - celery
  - click
  - datapane>=0.10.0
  - deap
  - flake8
  - flask
  - flask-login
  - flask-migrate
  - flask-moment
  - flask-sqlalchemy
  - flask-wtf
  - fbprophet
  - gdown
  - gym
  - ipykernel
  - itsdangerous
  - jinja2
  - joblib
  - jupyter
  - jupyterlab
  - lightgbm
  - matplotlib
  - mypy
  - nb_black
  - networkx
  - numpy
  - opencv
  - openpyxl
  - pandas
  - pandas-datareader
  - pillow
  - plotly
  - pre-commit
  - pyarrow
  - pylint
  - pyspark
  - pytest
  - pytest-cov
  - pytest-env
  - python-dotenv
  - pytorch
  - py-xgboost
  - pyyaml
  - reportlab
  - requests
  - seaborn
  - scipy
  - scikit-learn
  - scikit-image
  - simpy
  - sqlalchemy
  - statsmodels
  - sympy
  - tabulate
  - tensorflow-gpu=2.3.*
  - tensorboard
  - torchvision
  - tqdm
  - types-six
  - types-pyyaml
  - umap-learn
  - vega
  - vega_datasets
  - werkzeug
  - wtforms
  - pip
  - pip:
      - sklearn-deap2
      - sklearn-json
