name: research
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - cudatoolkit=10.1
  - cudnn=7.6
  - h5py
  - hdf5
  - altair
  - altair_saver
  - altair_viewer
  - black
  - bokeh
  - boto3
  - catboost
  - click
  - dash
  - datapane>=0.10.0
  - deap
  - dlib
  - flake8
  - gdown
  - gym
  - ipykernel
  - ipywidgets
  - isort
  - joblib
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - lightgbm
  - matplotlib
  - mypy
  - networkx
  - nltk
  - numpy
  - opencv
  - openpyxl
  - pandas
  - pandas-datareader
  - panel
  - pillow
  - plotly
  - pre-commit
  - pyarrow
  - pyspark
  - pytest
  - python-dotenv
  - pytorch
  - py-xgboost
  - pyyaml
  - reportlab
  - requests
  - seaborn
  - scipy
  - scikit-learn
  - scikit-image
  - simpy
  - statsmodels
  - sympy
  - tabulate
  - tensorflow-gpu=2.3.*
  - tensorboard
  - torchvision
  - tqdm
  - types-six
  - types-pyyaml
  - umap-learn
  - vega
  - vega_datasets
  - pip
  - pip:
      - sklearn-deap2
      - sklearn-json
